
services:
  blog-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/blogs_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - blogs-data:/data

volumes:
  blogs-data:
